services:
  django:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: password_django
    command:
      # python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/api
    ports:
      - "8000:8000"
    tty: true
    depends_on:
      - database

  database:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    container_name: password_database
    volumes:
      - mysql:/var/lib/mysql
    environment:
      # this variable is mandatory. this is the root user password
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      # name of a database
      MYSQL_DATABASE: mydb
      # create new user
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      TZ: "Asia/Tokyo"
    ports:
      - ":3306"
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./docker/nginx/config/password-manager-api.rito-dev.com:/etc/letsencrypt/live/password-manager-api.rito-dev.com:ro
    container_name: password_nginx
    ports:
      - "80:80"
      - "443:443"
volumes:
  mysql:
