services:
  django:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: password_django
    command:
      # python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/api
    ports:
      - "8000:8000"
    tty: true

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./docker/nginx/config/password-manager-api.rito-dev.com:/etc/letsencrypt/live/password-manager-api.rito-dev.com:ro
    container_name: password_nginx
    ports:
      - "80:80"
      - "443:443"
volumes:
  mysql:
