# Generated by Django 3.2.10 on 2023-03-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordmanage',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='passwordmanage',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='passwordmanage',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='passwordmanage',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
