# Generated by Django 3.2.10 on 2023-05-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordmanage',
            name='index',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name='passwordmanage',
            constraint=models.UniqueConstraint(fields=('user', 'group_id', 'index'), name='index_unique'),
        ),
    ]
