# Generated by Django 4.1 on 2023-07-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordmanage',
            name='password',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passwordmanage',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
