# Generated by Django 4.1 on 2023-07-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_passwordmanage_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordmanage',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
    ]
