# Generated by Django 3.2.10 on 2023-06-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_passwordmanage_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordmanage',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='passwordmanage',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.RemoveField(
            model_name='passwordmanage',
            name='custom_id',
        ),
        migrations.AddField(
            model_name='passwordmanage',
            name='custom',
            field=models.ManyToManyField(null=True, to='app.PasswordCustomField'),
        ),
    ]
