# Generated by Django 4.1 on 2023-07-18 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_passwordmanage_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_content', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('inquiry_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.inquirycategory')),
            ],
        ),
    ]
