# Generated by Django 3.2.10 on 2023-06-04 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230604_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordmanage',
            name='custom',
            field=models.ManyToManyField(blank=True, to='app.PasswordCustomField'),
        ),
    ]
