# Generated by Django 4.2.3 on 2023-07-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_inquiry_created_at_inquiry_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('UNREAD', 'Unread'), ('READ', 'Read'), ('IN_PROGRESS', 'In Progress'), ('ANSWERED', 'Answered'), ('CLOSED', 'Closed')], default='UNREAD', max_length=20),
        ),
    ]
