# Generated by Django 3.2.10 on 2023-07-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_passwordmanage_custom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordmanage',
            name='index',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
