# Generated by Django 4.1.5 on 2023-01-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_passwordmanage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='passwordmanage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
