# Generated by Django 3.2.10 on 2023-07-16 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_passwordmanage_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordmanage',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.passwordtag'),
        ),
    ]
